### ISSUE TITLE
Exceptions should be properly documented when applicable

### ISSUE THREAD

**Issue by Youssef1313** [MicrosoftDocs/winapps-winrt-api#73]
Seeing an exception like this doesn't give useful info:

```
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IContentControlMethods.set_Content(IObjectReference _obj, Object value)
   at Microsoft.UI.Xaml.Controls.ContentControl.set_Content(Object value)
```

and the documentation doesn't mention what exceptions can be thrown from `ContentControl.set_Content` and when those exceptions occur.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34fc9f94-5d93-0f2e-28d8-dffaa06b8254
* Version Independent ID: 34fc9f94-5d93-0f2e-28d8-dffaa06b8254
* Content: [ContentControl.Content Property (Microsoft.UI.Xaml.Controls) - Windows App SDK](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.contentcontrol.content?view=windows-app-sdk-1.3)
* Content Source: [winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/ContentControl.xml](https://github.com/MicrosoftDocs/winapps-winrt-api/blob/docs/winapps-winrt-build/xml/Microsoft.UI.Xaml.Controls/ContentControl.xml)
* Product: **reunion**
* Technology: **reunion-reference**
* GitHub Login: @jwmsft
* Microsoft Alias: **jimwalk**

**Comment by GrantMeStrength** [comment]
Closing this issue due to age (filed before 2024). If this is still relevant, please reopen or file a new issue with updated details. Thank you for your contribution!
